insert into EXCHANGE_VALUE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) values(10000,'USD','INR',70,0);
insert into EXCHANGE_VALUE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) values(10001,'EUR','INR',80,0);
insert into EXCHANGE_VALUE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) values(10002,'AUD','INR',50,0);